language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"

# install dependencies
install: 
    - pip install .
    - pip install pathlib

# run tests
# TODO: figure out a way to include menpo rather than skipping the test.
script:
    - nosetests --ignore-files test_menpo_related.py
